export const maladieChronique = [
  "Asthme",
  "cancer",
  "Diabète",
  "Épilepsie",
  "Hypertension artérielle ",
  "Hypercholestérolémie ",
  "Insuffisance hépatique",
  "Insuffisance rénale ",
  "Troubles cardiaques",
  "Troubles de la coagulation",
];

export const pathologie = [
  "Asthénie",
  "Arthrose",
  "Asthme",
  "Aphte",
  "Acné",
  "Ballonnements",
  "Bouffées de chaleur",
  "Brulure",
  "Bronchite",
  "Chute de cheveux",
  "Calculs biliaires",
  "Cicatrices",
  "Coup de soleil ",
  "Constipation",
  "Cancer",
  "Diabète",
  "Digestion difficile ",
  "Douleurs Abdominales",
  "Douleurs de menstruation",
  "Dépression",
  "Détox",
  "Diarrhée",
  "Eczéma",
  "Épilepsie",
  "Fièvre",
  "Jambes lourdes",
  "Hémorroides",
  "Hypercholestérolémie",
  "Hypertension artérielle",
  "Infection Urinaire ",
  "Insuffisance rénale",
  "Insuffisance hépatique",
  "Insomnie",
  "Grippe",
  "Gingivite ",
  "Laryngite",
  "Mal de gorge",
  "Migraine",
  "Maux de Tete",
  "Mal des transports",
  "Manque d'appétit",
  "Ménopause",
  "Mauvaise Haleine",
  "Nausées et Vomissements",
  "Oedème",
  "Obésité",
  "Psoriasis",
  "Pharyngite",
  "Piqure d'insectes",
  "Prurit",
  "Rhumatisme",
  "Rhinite",
  "Rhume",
  "Reflux gastro oesophagien",
  "Sinusite",
  "Stress ",
  "Saignement de nez",
  "Toux ",
  "Toux grasse",
  "Transpiration",
  "Troubles de mémoire ",
  "Troubles cardiaques",
  "Troubles de coagulation",
  "Ucère",
  "Vertiges",
  "Vergetures",
  "Varices",
];

export const ProductData = [
   
];
